### ISSUE TITLE
External resources are not in the classpath

### ISSUE THREAD

**Issue by pandrez** [gradle/gradle-java-modules#6]
Hi!

I forked the project ([https://github.com/pandrez/building-java-9-modules](url)) and modified the last step to include log4j2 as a dependency of the fairy module. I created a src/main/resources folder and added a log4j2.xml into it. 

If I run ./gradlew run, the first output line states that log4j2.xml cannot be found. 

It seems that this file is not added to the module path.

Am I doing something wrong or is there an issue here?

**Comment by rgoldberg** [comment]
The issue is that the `run` task is using the exploded output folder (`build/classes/java/main`), not the `libs/fairy.jar` output from the `jar` task.

The contents of `src/main/resources` will included in `libs/fairy.jar`, so if you ran that, everything would be fine.

The original plugin adds `build/resources/main` to the `--module-path`. That, however, is useless since that directory does not itself contain a module, and isn't associated with any module by being in `--module-path`.

Instead, `src/main/resources` should be removed from `--module-path`, and it should be in:

```
--patch-module org.gradle.fairy.app=build/resources/main
```

Which specifies that the contents of `build/resources/main` should be patched into (i.e. considered as part of) the `org.gradle.fairy.app` module.

I'll fix this in my fork.

**Comment by jjohannes** [comment]
Gradle 6.4 now supports Java Modules directly. There we use the Jar instead of folders in many places to mitigate this issue.
